/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boton;

/**
 *
 * @author black
 */
/*
public class Boton {
    
}*/

import static Boton.Prueba.botones;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToolBar;



public class Boton extends javax.swing.JFrame implements ActionListener{
    Caminos camino = new Caminos();     //esta es una clase donde se tiene el algoritmo para obtener el camino entre dos puntos
    int filas = 15, columnas = 15, x=0, y=0; //se define el tamnaño de la matriz, asi como las variables para las coordenadas
    JButton [][] botones = new JButton[filas][columnas]; //es un matriz de botones de acuerdo alas filas y columnas
    JButton btnCrear;
    JLabel pasitoslbl;
    Boton ventana1;
    JToolBar barraHerramientas = new JToolBar();
    /**
     * Creates new form Boton
     */
    public Boton() {
        
        setLayout(null);    
        initComponents();       //el ciclo for permitira inicilizar cada uno de los botones y posicionarlo dentro del frame
        setLocationRelativeTo(null);
        btnCrear = new JButton("NUEVO");
        btnCrear.setBounds(480, 0, 100, 30);
        add(btnCrear);
        
        btnCrear.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              //etiqueta.setText("Has pulsado el botón ");
                try {
                    Boton ventana = new Boton();
                ventana.setVisible(true);
                ventana1.dispose();
                } catch (Exception ex) {
                    
                }
                
            }	
          });
        
        
        pasitoslbl = new JLabel("Total Pasos: ");
        pasitoslbl.setBounds(480, 60, 100, 30);
        add(pasitoslbl);
        
        
        for(int i=0; i<filas; i++){
            for(int j=0; j<columnas; j++){
                botones[i][j] = new JButton();
                botones[i][j].setBounds(y, x, 30, 30);  //cada boton tendra una dimesion de 15x15 pixeles, debido a la cantidad
                botones[i][j].addActionListener(this); //ademas de agregar el evento para saber al momento de hacer click 
                add(botones[i][j]);
                x += 30;        //debido al espacio de la ventana la separacion de cada boton sera de 10 pixeles
            }               //tanto en el eje x como en el eje y
            x = 0;
            y += 30;
        }
        camino.botones = botones;   //una ves inicializado los botones se comparten con la clase de busqueda de la ruta
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Boton().setVisible(true);
                try {
                    Boton ventana1 = new Boton();
                    ventana1.setVisible(true);
                } catch (Exception e) {
                }
                
                //JOptionPane.showMessageDialog(null,"Marca 5 puntos sobre la matriz");
            }
        });
    }
    
    

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    if (e.getSource() == botones[i][j]) {
                        if(camino.contador<6){
                            if(camino.contador==0){
                                botones[i][j].setBackground(Color.red);
                                botones[i][j].setText("1");
                            }else if(camino.contador==4){
                                botones[i][j].setBackground(Color.blue);
                                botones[i][j].setText("6");
                            }else{
                                botones[i][j].setText(" "+camino.contador);
                                botones[i][j].setBackground(Color.black);
                            }
                            camino.guardar(botones[i][j].getY(), botones[i][j].getX());
                        }
                        if(camino.contador==5){
                            camino.Listado();
                            pasitoslbl.setText("Total Pasos: " + camino.pasos);
                        }
                    }
                }
            }
        } catch (Exception ex) {
            for (int i = 0; i < 15; i++) {
            for (int j = 0; j < 15; j++) {
                botones[i][j].setEnabled(false);
            }
        }
            //botones[][].setEnabled(true);
        }
        
    }
    

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
